// <auto-generated />
using ImageFinder.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImageFinder.Dal.Migrations
{
    [DbContext(typeof(ImageDbContext))]
    partial class ImageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("ImageFinder.Dal.ImageDbContext+Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Url = "https://api.dicebear.com/8.x/pixel-art/png?seed="
                        },
                        new
                        {
                            Id = 2,
                            Url = "https://api.dicebear.com/8.x/pixel-art/png?seed="
                        },
                        new
                        {
                            Id = 3,
                            Url = "https://api.dicebear.com/8.x/pixel-art/png?seed="
                        },
                        new
                        {
                            Id = 4,
                            Url = "https://api.dicebear.com/8.x/pixel-art/png?seed="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
